[protractor.dev]
seleniumAddress = 'http://localhost:4444/wd/hub'
testPortalAddress = 'http://cov.geojb'
generateCoverageReport = true


[protractor.prod]
seleniumAddress = 'http://localhost:4444/wd/hub'
testPortalAddress = 'http://geojb'
generateCoverageReport = false

